version: '3.8'

services:

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: iopl-postgres
    environment:
      POSTGRES_DB: iopl
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwertz$123
    ports:
      - "5432:5432"
    networks:
      - backend

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: iopl-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: qwertz$123
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    networks:
      - backend

  # Spring Boot Application
  spring-boot-app:
    image: dinnguyen1495/iopl:latest
    container_name: iopl-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/iopl
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: qwertz$123
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge