FROM openjdk:17-jdk-alpine
LABEL authors="minhd"
MAINTAINER wubba141
COPY target/LibraryManager-0.0.1-SNAPSHOT.jar LibraryManager-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/LibraryManager-0.0.1-SNAPSHOT.jar"]